name: Update Azure Data

on:
  push:
    branches:
      - main  # Change to your default branch name

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Python Script
        env:
          AZURE_SERVER_NAME: ${{ secrets.AZURE_SERVER_NAME }}
          AZURE_DATABASE_NAME: ${{ secrets.AZURE_DATABASE_NAME }}
          AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
          AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
          SMARTSHEET_ACCESS_TOKEN: ${{ secrets.SMARTSHEET_ACCESS_TOKEN }}
          SMARTSHEET_SHEET_ID: ${{ secrets.SMARTSHEET_SHEET_ID }}
        run: python your_script.py
