name: Smartsheet to Azure SQL CI/CD

on: 
  push:  
    branches:
      - master  # Change to the branch you want to trigger the workflow on

jobs:
  data_transfer:
    runs-on: ubuntu-latest

    steps:
      - name: smartsheettosql/updating1.yml
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          pip install pyodbc
          pip install smartsheet-python-sdk

      - name: Run Smartsheet to SQL Script
        run: |
          python updating.py  # Use the correct path to your Python script
        env:
          AZURE_SQL_SERVER_NAME: ${{ secrets.AZURE_SERVER_NAME }}
          AZURE_SQL_DB_NAME: ${{ secrets.AZURE_DATABASE_NAME }}
          AZURE_SQL_USERNAME: ${{ secrets.AZURE_USERNAME }}
          AZURE_SQL_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
          SMARTSHEET_ACCESS_TOKEN: ${{ secrets.SMARTSHEET_ACCESS_TOKEN }}
          SMARTSHEET_SHEET_ID: ${{ secrets.SMARTSHEET_SHEET_ID }}
